# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BUILD_SOURCE_DIRS "E:/Project/hmllm/kylin-messenger;E:/Project/hmllm/kylin-messenger/build-win")
set(CPACK_CMAKE_GENERATOR "Ninja")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_DEBIAN_PACKAGE_DEPENDS "libqt5core5a, libqt5widgets5, libqt5network5, libqt5gui5, zlib1g")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Kylin Messenger Team")
set(CPACK_DEBIAN_PACKAGE_PRIORITY "optional")
set(CPACK_DEBIAN_PACKAGE_SECTION "net")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "D:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "kylin-messenger built using CMake")
set(CPACK_GENERATOR "DEB")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "E:/Project/hmllm/kylin-messenger/build-win;kylin-messenger;ALL;/")
set(CPACK_INSTALL_PREFIX "C:/Program Files (x86)/kylin-messenger")
set(CPACK_MODULE_PATH "D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6;D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6/3rdparty/kwin;D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6;D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6/3rdparty/extra-cmake-modules/find-modules;D:/Qt/6.9.3/mingw_64/lib/cmake/Qt6/3rdparty/kwin")
set(CPACK_NSIS_DISPLAY_NAME "kylin-messenger 1.0.1")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
set(CPACK_NSIS_PACKAGE_NAME "kylin-messenger 1.0.1")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "D:/Qt/Tools/mingw1310_64/bin/objcopy.exe")
set(CPACK_OBJDUMP_EXECUTABLE "D:/Qt/Tools/mingw1310_64/bin/objdump.exe")
set(CPACK_OUTPUT_CONFIG_FILE "E:/Project/hmllm/kylin-messenger/build-win/CPackConfig.cmake")
set(CPACK_PACKAGE_CONTACT "your.email@example.com")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "D:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "P2P LAN Messenger with AI Features")
set(CPACK_PACKAGE_FILE_NAME "kylin-messenger-1.0.1-win64")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "kylin-messenger 1.0.1")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "kylin-messenger 1.0.1")
set(CPACK_PACKAGE_NAME "kylin-messenger")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "Kylin Messenger Team")
set(CPACK_PACKAGE_VERSION "1.0.1")
set(CPACK_PACKAGE_VERSION_MAJOR "1")
set(CPACK_PACKAGE_VERSION_MINOR "0")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_READELF_EXECUTABLE "D:/Qt/Tools/mingw1310_64/bin/readelf.exe")
set(CPACK_RESOURCE_FILE_LICENSE "D:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Templates/CPack.GenericLicense.txt")
set(CPACK_RESOURCE_FILE_README "D:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "D:/ST/STM32CubeCLT_1.18.0/CMake/share/cmake-3.28/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_7Z "ON")
set(CPACK_SOURCE_GENERATOR "7Z;ZIP")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "E:/Project/hmllm/kylin-messenger/build-win/CPackSourceConfig.cmake")
set(CPACK_SOURCE_ZIP "ON")
set(CPACK_SYSTEM_NAME "win64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "win64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "E:/Project/hmllm/kylin-messenger/build-win/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
